---
# tasks file for codedeploy
- name: install pip to install boto
  yum:
    name: pip
    state: present

- name: install boto
  pip:
    name: boto
    state: present    
    
- name: Installs and starts AWS CodeDeploy Agent
  aws_codedeploy:
    enabled: yes
