---
# tasks file for nodejs
- name: install the rhel rpm from a remote repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
    
- name: install the latest version of npm from rhel rpm
  yum:
    name: npm
    state: present
    
- name: install the latest version of node from rhel rpm
  yum:
    name: nodejs
    state: present