---
# tasks file for helloworld
- name: Copying the application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld

- name: Copying the service file
  copy:
    src: helloworld.service
    dest: /etc/systemd/system/helloworld.service
    owner: root
    group: root
    mode: 0644

- name: enable service HelloWorld
  systemd:
    name: helloworld
    enabled: yes
    
- name: Starting the HelloWorld node service
  systemd:
    name: helloworld
    state: started